# Generated by Django 4.2.11 on 2026-03-11 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('total_scraped', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('cache_enabled', models.BooleanField(default=True)),
                ('cache_ttl_seconds', models.IntegerField(default=3600)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Scraper Status',
            },
        ),
        migrations.CreateModel(
            name='PCPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type', models.CharField(choices=[('cpu', 'CPU'), ('gpu', 'GPU'), ('motherboard', 'Motherboard'), ('memory', 'Memory'), ('storage', 'Storage'), ('psu', 'Power Supply'), ('case', 'Case')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('specs', models.JSONField(default=dict)),
                ('url', models.URLField()),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('part_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.IntegerField()),
                ('usage', models.CharField(choices=[('gaming', 'Gaming'), ('video_editing', 'Video Editing'), ('general', 'General')], max_length=20)),
                ('total_price', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cfg_case', to='scraper.pcpart')),
                ('cpu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cfg_cpu', to='scraper.pcpart')),
                ('gpu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cfg_gpu', to='scraper.pcpart')),
                ('memory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cfg_memory', to='scraper.pcpart')),
                ('motherboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cfg_mobo', to='scraper.pcpart')),
                ('psu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cfg_psu', to='scraper.pcpart')),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cfg_storage', to='scraper.pcpart')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
